"""add like comment

Revision ID: bd65e883880c
Revises: 8831bf91a498
Create Date: 2022-10-21 15:44:56.229007

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bd65e883880c'
down_revision = '8831bf91a498'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('likes', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'likes')
    # ### end Alembic commands ###
